### PR TITLE
basic implementation of volumes

### PR DESCRIPTION
**Pull request by nupfel**

### CODE REVIEW

**Comment by bartekrutkowski** [comment]
@nupfel Hi, if you'd like to see these features merged, feel free to send PR's (obviously, properly adjusted) to the fork I've just created exactly for the reason of getting new features: https://github.com/bartekrutkowski/iocell/tree/develop

**Comment by skarekrow** [comment]
I deleted @bartekrutkowski's comment as I don't like advertising on my project. iocage is not dead (it says that much on the front) and I am very much still doing work on this on behalf of iXsystems. It will come when it's ready.

As for the PR, I'm of two minds. I really think this sort of thing should be in `develop`. But I like the idea. I'll think on this some more, thanks for the PR!

**Comment by bartekrutkowski** [comment]
@skarekrow I kindly, but strongly disagree here with you. What is says in the readme is "No longer supported". The fact that next sentence promises some rewrite is actually worthless, when it comes to current iocage users, as it gives absolutely no information on when it will be available, will it be supporting existing iocage installations and so on, giving existing and potential iocage users absolutely zero information about future of their environments.

What I did in the PR's was simply informing the users, that I've forked iocage into iocell with only one goal - providing existing iocage userbase with necessary updates in changing environment (new FreeBSD releases, VNET being fixed, so on and so forth) while you can work on the rewrite for months or years, or however long it take. I think this is the best thing to do for the users, since you've abandoned the project and also refused to release it to people willing to support it further at the same time, leaving iocage users in a really bad spot.

**Comment by skarekrow** [comment]
@bartekrutkowski Let's not get dramatic. I haven't made any statements on support as I figured it was a given that there would be a migration path for my users like with any major change I did. I set the precedent then, and I will continue that trend.

So to make it absolutely 100% clear, yes current iocage users will be supported. In regards to new FreeBSD releases, those are unlikely to affect iocage, and certainly not before the rewrite is available. I'm all about supporting the users, but I also don't appreciate the fiction. I have not abandoned the project, I have abandoned *additional development personally* on the shell version. That is a clear difference. 

There is a clear narrative you are trying to drive and have been since the rewrite was announced. To be clear, I'm fine you have a fork. I'm not fine you advertise it on any of my issues or PR's. It's fine if you disagree with the reasons, or are upset that it's happening. I hope to change your mind one day, but ultimately I have to move this project in the direction I want.

I would also point out that I haven't refused anyone from supporting this. There has been no direct contact with me personally by any party interested in doing so. But I'm also unwilling to blindly hand it over to people I haven't met. It's the only way I can ensure iocage remains what it's meant to be and not morph into something entirely different.

That being said, you can see that this is titled _iocage/iocage_ and not _skarekrow/iocage_. This is a *project*. Not just mine, but a team. There are multiple people who have my express consent to push changes as they see fit, moderate and help. My good friend @pr1ntf is an excellent example of someone who has done just that. This is far from a one man show. We have many PR's by many fantastic contributors who pop in when they feel like doing so. They aren't expected to help me maintain this, and they also haven't expressed interest.

I can't hardly thrust that on others. You also have not expressed interest publicly or privately @bartekrutkowski. We could have had a discussion instead of a fork. That's usually what happens when the party is interested in cooperation instead of competition :)

With all that being said, this is open source. I can't stop you or refuse anyone of anything. I don't intend to. Fork, enhance, enjoy. That's the spirit this has been written in, and it's what I will do going forth. Let's not muddy up this issue with any more bickering. You know my email, feel free to discuss this more with me if you want, as I'd like us to work together and not against each other. But to each their own.

Thanks for the interest.

**Comment by bartekrutkowski** [comment]
@skarekrow I am very suprised by almost everything in your reply. For one, you seem to be contradicting to your own statements from few months ago, and two, we've *had* private discussion on keeping iocage supported, where I've expressed my interest and concerns about just announcing the project dead and not releasing it to other people willing to drive it further, but you've declined then. Has it changed? The only reason I've went on with the fork was your stance on iocage and the possibility of driving it further in existing shape.

**Comment by norbu09** [comment]
Could we get back to the actual PR, we use this in production and it would be awesome to have this merged. The above discussion is important but maybe better at home in a separate issue.

**Comment by skarekrow** [comment]
I'm not certain I really want to merge this into the `master` branch as that's essentially the last stable branch. I prefer small bug fixes. Any large feature additions should be made to `develop` as that is the branch's intent. There's sufficient divergence between `master` and `develop` that I know this won't be trivial to port, but it doesn't make any sense the development tree is lacking features the stable one has.

So I won't be merging this into master. My apologies @nupfel for the off topic discussion. This is a very thorough PR, which is why I haven't jumped at immediately merging. If you could please base this against develop, I'd be happy to merge it. As I do think this is quite important as @norbu09 has stated.

**Comment by nupfel** [comment]
sorry, but i don't believe that the develop branch will ever be merged into master any time soon and by that i mean within days not months given that you are working on a golang version of iocage, which is great, but still a long way out. feel free to delete the PR if you like or merge it, up to you.

**Comment by skarekrow** [comment]
Well I had more time to think about this and figured what is the harm in merging this as I won't be making another release for iocage_legacy's `master` branc(never say never? I dunno.) If the user wants volumes, they can use the `master` branch off GitHub with your changes, and if something goes wrong they know exactly what they signed up for. I look forward to this being ported to the new iocage, it's a great idea :)

Sorry it took so long, but I appreciate the PR!

**Pull request merged**
